# ---------- BUILD STAGE ----------
FROM node:20-alpine AS builder
WORKDIR /app

COPY package*.json ./
RUN npm ci

# Copy toàn bộ code
COPY . .

# 🔥 QUAN TRỌNG: Copy file .env.production vào để Next.js tự đọc khi build
# Lưu ý: File này phải nằm cùng thư mục với Dockerfile trên máy host
COPY .env.production .env.production

# Lúc này npm run build sẽ tự nhặt biến môi trường trong .env.production
RUN npm run build

# ---------- RUN STAGE ----------
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production

COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/next.config.* ./

# Copy file env sang cả runner để lúc chạy server (runtime) nó đọc các biến Server-side (như NEXTAUTH_SECRET)
COPY --from=builder /app/.env.production ./.env.production

EXPOSE 3000
CMD ["npm", "start"]