version: "3.8"

services:
  jobpilot-fe:
    container_name: jobpilot-fe
    image: jobpilot-fe:latest
    ports:
      - "3000:3000"
    restart: unless-stopped

    environment:
      NODE_ENV: production

      # ===== APP =====
      NEXT_PUBLIC_APP_URL: https://jobpilot.id.vn

      # ===== NEXT AUTH =====
      NEXTAUTH_SECRET: your-long-random-string

      # ===== API =====
      NEXT_PUBLIC_API_TIMEOUT: "20000"
      NEXT_PUBLIC_API_BASE_URL: https://jobpilot-nodejs-api.jobpilot.id.vn
      NEXT_PUBLIC_API_JAVA_BASE_URL: https://jobpilot-java-api.jobpilot.id.vn

      # ===== FIREBASE (PUBLIC ONLY) =====
      NEXT_PUBLIC_FIREBASE_API_KEY: "AIzaSyCCX4A1LA0seSgsjv8J3NbPOGgXIhoKTOg"
      NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: "jobpilot-432f1.firebaseapp.com"
      NEXT_PUBLIC_FIREBASE_PROJECT_ID: "jobpilot-432f1"
      NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: "jobpilot-432f1.firebasestorage.app"
      NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: "605788664856"
      NEXT_PUBLIC_FIREBASE_APP_ID: "1:605788664856:web:2d1a741c7ce30d65963f6d"
      NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: "G-71C9VHRFXC"

      # ====== INTERNAL ======
      INTERNAL_API_KEY: "some-long-random-internal-key"
      JWT_SECRET: "JWT_SECRET"
